2020-05-18 14:43:25,281 ERROR: Exception on /edit_profile [GET] [in c:\users\user\mblog\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\user\mblog\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\user\mblog\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\user\mblog\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\user\mblog\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\user\mblog\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\user\mblog\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\user\mblog\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\User\PycharmProjects\mblog\app\routes.py", line 115, in edit_profile
    return render_template('edit_profile.html', title='Edit Profile',
  File "c:\users\user\mblog\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "c:\users\user\mblog\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\user\mblog\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\user\mblog\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\user\mblog\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\User\PycharmProjects\mblog\app\templates\edit_profile.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\User\PycharmProjects\mblog\app\templates\base.html", line 30, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\User\PycharmProjects\mblog\app\templates\edit_profile.html", line 6, in block "content"
    {{ form.hidden_tag() }}
  File "c:\users\user\mblog\lib\site-packages\flask_wtf\form.py", line 134, in hidden_tag
    u'\n'.join(text_type(f) for f in hidden_fields(fields or self))
  File "c:\users\user\mblog\lib\site-packages\flask_wtf\form.py", line 134, in <genexpr>
    u'\n'.join(text_type(f) for f in hidden_fields(fields or self))
  File "c:\users\user\mblog\lib\site-packages\flask_wtf\form.py", line 124, in hidden_fields
    for f in fields:
  File "c:\users\user\mblog\lib\site-packages\wtforms\form.py", line 56, in __iter__
    return iter(itervalues(self._fields))
AttributeError: 'EditProfileForm' object has no attribute '_fields'
2020-05-18 14:44:24,507 INFO: Flaskblog startup [in C:\Users\User\PycharmProjects\mblog\app\__init__.py:48]
2020-05-18 14:44:26,567 ERROR: Exception on /edit_profile [GET] [in c:\users\user\mblog\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\user\mblog\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\user\mblog\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\user\mblog\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\user\mblog\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\user\mblog\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\user\mblog\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\user\mblog\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\User\PycharmProjects\mblog\app\routes.py", line 115, in edit_profile
    return render_template('edit_profile.html', title='Edit Profile',
  File "c:\users\user\mblog\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "c:\users\user\mblog\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\user\mblog\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\user\mblog\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\user\mblog\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\User\PycharmProjects\mblog\app\templates\edit_profile.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\User\PycharmProjects\mblog\app\templates\base.html", line 30, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\User\PycharmProjects\mblog\app\templates\edit_profile.html", line 6, in block "content"
    {{ form.hidden_tag() }}
  File "c:\users\user\mblog\lib\site-packages\flask_wtf\form.py", line 134, in hidden_tag
    u'\n'.join(text_type(f) for f in hidden_fields(fields or self))
  File "c:\users\user\mblog\lib\site-packages\flask_wtf\form.py", line 134, in <genexpr>
    u'\n'.join(text_type(f) for f in hidden_fields(fields or self))
  File "c:\users\user\mblog\lib\site-packages\flask_wtf\form.py", line 124, in hidden_fields
    for f in fields:
  File "c:\users\user\mblog\lib\site-packages\wtforms\form.py", line 56, in __iter__
    return iter(itervalues(self._fields))
AttributeError: 'EditProfileForm' object has no attribute '_fields'
2020-05-18 14:46:08,308 ERROR: Exception on /edit_profile [GET] [in c:\users\user\mblog\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\user\mblog\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\user\mblog\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\user\mblog\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\user\mblog\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\user\mblog\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\user\mblog\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\user\mblog\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\User\PycharmProjects\mblog\app\routes.py", line 115, in edit_profile
    return render_template('edit_profile.html', title='Edit Profile',
  File "c:\users\user\mblog\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "c:\users\user\mblog\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\user\mblog\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\user\mblog\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\user\mblog\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\User\PycharmProjects\mblog\app\templates\edit_profile.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\User\PycharmProjects\mblog\app\templates\base.html", line 30, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\User\PycharmProjects\mblog\app\templates\edit_profile.html", line 6, in block "content"
    {{ form.hidden_tag() }}
  File "c:\users\user\mblog\lib\site-packages\flask_wtf\form.py", line 134, in hidden_tag
    u'\n'.join(text_type(f) for f in hidden_fields(fields or self))
  File "c:\users\user\mblog\lib\site-packages\flask_wtf\form.py", line 134, in <genexpr>
    u'\n'.join(text_type(f) for f in hidden_fields(fields or self))
  File "c:\users\user\mblog\lib\site-packages\flask_wtf\form.py", line 124, in hidden_fields
    for f in fields:
  File "c:\users\user\mblog\lib\site-packages\wtforms\form.py", line 56, in __iter__
    return iter(itervalues(self._fields))
AttributeError: 'EditProfileForm' object has no attribute '_fields'
2020-05-18 14:46:53,594 INFO: Flaskblog startup [in C:\Users\User\PycharmProjects\mblog\app\__init__.py:48]
